title: Mobility

author: The Mobility team

description: Mobility is an open-source solution to compute the carbon emissions due to the mobility of a local population.
  
theme: minima

minima:
 header_pages:
   - about.md
