title: Mobility

author: The Mobility team

description: Mobility is an open-source solution to compute the carbon emissions due to the mobility of a local population.
  
remote_theme: daattali/beautiful-jekyll@5.0.0

avatar: "logo.png"
